### ISSUE TITLE
Unable to sign up with mobile devices

### ISSUE THREAD

**Issue by Csun01** [flxcn/volunteer-nexus#72]
After pressing "view" for an opportunity, the screen does not let the user press "Sign Up."
![IMG_1915](https://user-images.githubusercontent.com/42942891/135193486-491c1cb6-6383-4cde-a1b6-ae8553382c93.PNG)

**Comment by Csun01** [comment]
https://stackoverflow.com/questions/44181031/bootstrap-modal-disabled

**Comment by flxcn** [comment]
Fixed. Problem occurred due to the fact that modals are generated inside the Opportunities table, which led to a conflict since the parent container of the modals, the table, needed to be hidden behind the modal-backdrop, but the modals themselves needed to be in front of the modal-backdrop. This conflict resulted in a z-index mismatch.
https://github.com/flxcn/volunteer-nexus/commit/60b12c399ce426ece49e8bfa30135e737577945e
